557-feat-add-inspection-request-direct-email-option-for-chelsea-residents
LemmaLegalConsulting/docassemble-HousingCodeChecklist pull request #567
Opened 2024-11-04 18:01 UTC by KelizaMcGuire

<Type out your reasons for this PR>

Added question and code to email inspection requests directly to the City of Chelsea for residents who want to, updated download screen, and added conditional logic to inspection request instructions based on the user's address/answer to directly emailing letter.

<Add links to any solved issues here by using closing keywords>

Fixed #557 

### In this PR, I have:

<Check these boxes below before making the PR>
<To turn the box into a checkbox add an X inside it like this [X]>
<Remove spaces from the checkboxes so it's like this [X] not this [X ]>
<To Preview what your PR will look like, select "Preview" above>

* [X] Manually tested to ensure my PR is working
* [X] Ensured issues that this PR closes will be [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
* [X] Requested a review

<img width="555" alt="Screenshot 2024-10-30 at 2 36 10 PM" src="https://github.com/user-attachments/assets/adf15498-18e6-4246-bb38-bfe968b358a9">
<img width="1021" alt="Screenshot 2024-10-30 at 2 36 31 PM" src="https://github.com/user-attachments/assets/17f9e5f4-13e2-42ae-91f0-2ed9ce96647b">
<img width="709" alt="Screenshot 2024-10-30 at 2 38 55 PM" src="https://github.com/user-attachments/assets/3e5ac106-b37b-44d3-9179-1a7ae3dd01f6">
<img width="686" alt="Screenshot 2024-10-30 at 2 40 07 PM" src="https://github.com/user-attachments/assets/4b420bed-e979-4128-9ac7-03e5542d8898">
<img width="552" alt="Screenshot 2024-10-30 at 2 41 09 PM" src="https://github.com/user-attachments/assets/c2d8236e-4322-4cd0-9a14-ccd2cb00985f">
<img width="665" alt="Screenshot 2024-10-30 at 2 55 36 PM" src="https://github.com/user-attachments/assets/dc542417-03b0-4d6c-99c3-7d57eb7f96b4">

2024-11-04 18:06 UTC, KelizaMcGuire commented
@nonprofittechy just so you know the email is currently sent from no-reply@lemmalegal.com. We could add a reply_to email for the user they have one filled out, but many potentially won't have one filled out.

2024-11-05 18:28 UTC, nonprofittechy requested changes
Let's change the yes/no buttons to yes/no radio with the regular next button instead (we have gotten this advice on a lot of usability audits)

2024-11-06 18:04 UTC, KelizaMcGuire commented
Updated the question to yesnoradio!

2024-11-06 21:15 UTC, nonprofittechy approved these changes

2024-11-06 21:16 UTC, merged